services:
  postgres:
    container_name: postgres-sql-chatify
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chatify_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - chatify
    restart: unless-stopped
  keycloak:
    container_name: keycloak-chatify
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - chatify
    command: start-dev

networks:
  chatify:
    driver: bridge

volumes:
  postgres:
    driver: local
